# Generated by Django 3.2.11 on 2022-12-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0004_cliente_organismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificador',
            name='numero',
            field=models.CharField(default=' ', max_length=250, verbose_name='Numero'),
        ),
    ]
