# Generated by Django 3.2.11 on 2022-12-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0005_certificador_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifico',
            name='asesorador',
        ),
        migrations.RemoveField(
            model_name='certifico',
            name='certificador',
        ),
        migrations.RemoveField(
            model_name='certifico',
            name='cliente',
        ),
    ]
