# Generated by Django 3.2.11 on 2022-12-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0006_auto_20221219_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictaminador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('cargo', models.CharField(choices=[('Especialista', 'Especialista'), ('Director(a)', 'Director(a)')], default='Especialista', max_length=250, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Dictaminador',
                'verbose_name_plural': 'Dictaminadores',
            },
        ),
    ]
