# Generated by Django 3.2.11 on 2022-12-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0010_asesorador_certificador_certifico_cliente_dictaminador_psi'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifico',
            name='estado',
            field=models.BooleanField(choices=[(False, 'Pendiente'), (True, 'Certificado')], default=False),
        ),
    ]
