# Generated by Django 3.2.11 on 2022-12-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0012_remove_certifico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifico',
            name='estado',
            field=models.BooleanField(choices=[(False, 'Pendiente'), (True, 'Certificado')], default=False),
        ),
    ]
