# Generated by Django 3.2.11 on 2022-12-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0013_certifico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictaminador',
            name='correo',
            field=models.CharField(default=' ', max_length=250, verbose_name='Correo'),
        ),
    ]
