# Generated by Django 3.2.11 on 2022-12-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0014_dictaminador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorador',
            name='cargo',
            field=models.CharField(default='Especialista', max_length=250, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='certificador',
            name='cargo',
            field=models.CharField(default='Especialista', max_length=250, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='psi',
            name='dictaminador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.dictaminador', verbose_name='Dictaminador'),
        ),
    ]
